quarkus.hibernate-orm.validate-in-dev-mode=false
quarkus.hibernate-orm.database.generation=none
quarkus.datasource.jdbc.url=${QUARKUS-DB}
quarkus.datasource.username=${QUARKUS-USER}
quarkus.datasource.password=${QUARKUS-PASSWORD}
quarkus.transaction-manager.default-transaction-timeout=300000
quarkus.datasource.jdbc.acquisition-timeout=300000
quarkus.datasource.jdbc.new-connection-sql=set datestyle='ISO, DMY'
quarkus.hibernate-orm.jdbc.timezone=America/Sao_Paulo
quarkus.banner.path=banner.txt

quarkus.http.port=8080
quarkus.http.host=0.0.0.0
quarkus.http.dev-mode=true
quarkus.http.dev-mode-allow-origin=*